Failure # 1 (occurred at 2020-05-09_11-16-21)
Traceback (most recent call last):
  File "/home/tom/.local/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 467, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/tom/.local/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 381, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/tom/.local/lib/python3.7/site-packages/ray/worker.py", line 1515, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.

